### ISSUE TITLE
Complementary color

### ISSUE THREAD

**Issue by cozzbie** [etoxin/complementary-colors#1]
```javascript
let mc = new compColors("#FFFFFF");
console.log(mc.complementary());

//[{r: 255, g: 255, b: 255}, {r: 255, g: 255, b: 255}]
```

Am I missing something or isnt the complementary supposed to be 0,0,0???

**Comment by etoxin** [comment]
this is weird. Looking into this.

**Comment by etoxin** [comment]
Ok, So this module uses the hue to rotate. White is absent of color so there is nothing to rotate. This module use a colour wheel. I'm going to look into this more.

**Comment by etoxin** [comment]
ok, that result is correct. Closing ticket.

**Comment by cozzbie** [comment]
Hmmm...learning everyday. So black is the complementary of what?
